### PR TITLE
Add some more colors

### PR DESCRIPTION
**Pull request by khazhyk**

### CODE REVIEW

**Comment by SunDwarf** [comment]
removes kerbal :-1:

**Comment by khazhyk** [comment]
Updated to add back kerbal

**Comment by khazhyk** [comment]
Also this pr sorts dark_green, which was out of alphabetical order.

**Comment by zeyla** [comment]
The word colour is ringing through my ears at this point and I don't know how to properly respond to this

**Comment by zeyla** [comment]
Merged in 4a14b92, thanks

**Pull request closed without merging**
